[project]
name = "tradeaggregator"
version = "1.1.0"
description = "Récupère des données de Boursorama et les écrit dans une feuille Google Sheets."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.2",
    "requests>=2.31.0",
    "gspread>=6.2.1",
    "google-auth>=2.21.0",
    "python-dotenv>=1.0.0",
]

[tool.setuptools.packages.find]
where = ["src"]
